### ISSUE TITLE
Does it support windows?

### ISSUE THREAD

**Issue by sm1999** [alker0/chezmoi.vim#28]
Problem with getting it to work on windows. Tested it in WSL and it works with the same config.

Vim version 8.2.3582

Minimal config .vim/vimrc

```
packadd chezmoi.vim 
syntax on
```

**Comment by alker0** [comment]
Currently tests are not enough on windows. If vim still hes not given a syntax highlight, reopen this.

**Comment by sm1999** [comment]
Thank you for the quick response!. Tested it and syntax highlight is applied.
