### ISSUE TITLE
Prevent vim from generating artefacts in .chezmoitemplates folder

### ISSUE THREAD

**Issue by j-xella** [alker0/chezmoi.vim#34]
`.chezmoitemplates` is a quite sensitive folder, because

 * chezmoi processes all the files there (note: this could soon [improve](https://github.com/twpayne/chezmoi/issues/1833))
 * if there is something wrong with any of the templates, chezmoi may exit. And since `.chezmoitemplates` folder is checked at the very beginning, this may block most of chezmoi functionality.
 
I believe it would be better to automatically disable additional files that vim may generate (swaps, backups) when editing files in `.chezmoitemplates` folder

**Comment by alker0** [comment]
Thank you for requesting the great feature. It should get to work via #35.
