### ISSUE TITLE
`.chezmoiignore` should highlighted as `conf.chezmoitmpl`

### ISSUE THREAD

**Issue by latipun7** [alker0/chezmoi.vim#43]
![image](https://user-images.githubusercontent.com/20012970/184290127-30370838-1602-45f0-827c-be09962a9126.png)

It would make sense `.chezmoiignore` is highlighted as `conf.chezmoitmpl` so the comments in that file is highlighted as comments.

**Comment by alker0** [comment]
Thank you for your describing with image. If it doesn't highlight, reopen this.
