### ISSUE TITLE
This plugin does not work with `lazy.nvim`

### ISSUE THREAD

**Issue by latipun7** [alker0/chezmoi.vim#57]
Neovim now have a [modern plugin manager](https://github.com/folke/lazy.nvim). Lot of users migrating to `lazy.nvim` now.

But this plugin does not work with `lazy.nvim` as that plugin manager has custom logic to load plugins.

I have opened issue to `lazy.nvim` in https://github.com/folke/lazy.nvim/discussions/369 with some details. Does this plugin can be supported to works with `lazy.nvim`?

Thank you.

**Comment by alker0** [comment]
Try setting `g:chezmoi#use_tmp_buffer` to on. It should works with any ordering of filetype detection.

Example:
```lua
{
  'alker0/chezmoi.vim',
  lazy = false,
  init = function()
    vim.g['chezmoi#use_tmp_buffer'] = true
  end,
}
```

**Comment by latipun7** [comment]
Thank you. This is working on my end. I haven't found a bug for now. You could close this issue.

Thank you 🎉
