### ISSUE TITLE
Add support for .chezmoiexternals and .chezmoidata

### ISSUE THREAD

**Issue by ryukisec** [alker0/chezmoi.vim#63]
chezmoi added the option to use the directories `.chezmoiexternals` ([v2.36.0](https://github.com/twpayne/chezmoi/releases/tag/v2.36.0)) and `.chezmoidata` ([v2.34.0](https://github.com/twpayne/chezmoi/releases/tag/v2.34.0)), where all files are interpreted as template, instead of a single file for each.

Files in those directories are currently not detected / handled correctly.

**Comment by alker0** [comment]
Thank you for your catching and good PR.
