### ISSUE TITLE
error when running `:0Gclog` (from `tpope/vim-fugitive`)

### ISSUE THREAD

**Issue by xfzv** [alker0/chezmoi.vim#68]
I keep getting the following error when running `:0Gclog` (from [`tpope/vim-fugitive`](https://github.com/tpope/vim-fugitive)) in any buffer (the file must be in a Git repository of course):

![image](https://github.com/alker0/chezmoi.vim/assets/78810647/f7241f19-53de-4cc7-8b1c-caa97f0f6e4c)

Sorry for using a screenshot, I don't know how to catch the error in a proper log.

- I'm using lazy.nvim as my plug-in manager.
- Disabling `chezmoi.vim` solves the issue.
- `:Git log` (still from `tpope/vim-fugitive`) doesn't print any error when `chezmoi.vim` is enabled.

- `vim-fugitive.lua`:
```lua
return {
  "tpope/vim-fugitive",
}
```

- `chezmoi.lua`:
```lua
return {
  "alker0/chezmoi.vim",
  init = function()
    vim.g["chezmoi#use_tmp_buffer"] = true
    vim.g["chezmoi#source_dir_path"] = "/home/xfzv/dotfiles"
  end,
}
```

**Comment by alker0** [comment]
Thank you for reporting the error. Calling `:0Gclog` opens a commit log list on the bottom. When the list is opening, this plugin tried detecting filetype of the list before. Please update this plugin. It should fix the issue.
