### ISSUE TITLE
The buffer is emptied each time I enter chezmoi managed buffer

### ISSUE THREAD

**Issue by Demianeen** [alker0/chezmoi.vim#72]
As the name suggests I have an issue tempting the buffer. My config:
```lua
  {
    -- highlighting for chezmoi files template files
    'alker0/chezmoi.vim',
    lazy = false,
    priority = 1100,
    opts = {
      -- use_tmp_buffer = true,
      source_dir_path = os.getenv('HOME') .. '/.local/share/chezmoi',
    },
    config = function(_, opts)
      for key, value in pairs(opts) do
        vim.g['chezmoi#' .. key] = value
      end
    end,
  },
```

It also don't copy into my buffer if I open already existing buffer:

https://github.com/alker0/chezmoi.vim/assets/51330172/5128c881-3dc4-4fc6-8298-07f863715a64

It is probably because I use the system clipboard as vim default one.

# Steps to Reproduce

1. Set system clipboard as default in nvim.
2. Copy something
3. Open a chezmoi managed file using Vim with the provided configuration.
4. Try to paste

What to do?

**Comment by alker0** [comment]
Hi. Thank you for your reporting the bug and showing steps for reproduction.
The PR #73 should fix the issue, via keeping the clipboard contents while this plugin uses the un-named register.

Please update this plugin and check if you can bring the clipboard contents into a chezmoi managed file.

**Comment by Demianeen** [comment]
Yeah, it is fixed. Thanks @alker0)
