### ISSUE TITLE
dot_zshrc/zshenv syntax is not set to zsh

### ISSUE THREAD

**Issue by moutazhaq** [alker0/chezmoi.vim#79]
filetype is correctly set to zsh but syntax is incorrectly set to conf instead of zsh.

I'm using nvim 0.10.0 and LazyVim.

**Comment by alker0** [comment]
Thank you for reporting this. However I'm still unable to reproduce this.

I need more information to be able to reproduce this:
1. Your Neovim is Windows version?
2. What does `nvim --version` show?
3. What does `chezmoi execute-template '{{ println .chezmoi.config.edit.hardlink }}'` show?
4. Does it change anything if you disable each your plugin except `chezmoi.vim`

**Comment by moutazhaq** [comment]
>     1. Your Neovim is Windows version?

I am on Linux.

>     2. What does `nvim --version` show?

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

>     3. What does `chezmoi execute-template '{{ println .chezmoi.config.edit.hardlink }}'` show?

`true`

>     4. Does it change anything if you disable each your plugin except `chezmoi.vim`

No.

**Comment by alker0** [comment]
Thank you for providing the additional information. It has helped me find a bug that could be causing this issue. Please update the plugin and check if it now works correctly.

**Comment by moutazhaq** [comment]
Thanks, that fixed the issue.
